In [1]:
import pandas as pd
import numpy as np

In [45]:
df = pd.read_csv('data_sets/data/survey_results_public.csv')

In [46]:
df

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I agree,None of these,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,...,1-2 times a week,10+ times a week,Never,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,285000.0
2,3,I agree,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,...,6-10 times a week,6-10 times a week,3-5 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,250000.0
3,4,I agree,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Friend or family member;Other online...,Formal documentation provided by the owner of ...,...,1-2 times a week,10+ times a week,1-2 times a week,15-30 minutes a day,30-60 minutes a day,Automated testing;Continuous integration (CI) ...,NaN,Appropriate in length,Easy,156000.0
4,5,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,...,1-2 times a week,1-2 times a week,3-5 times a week,60-120 minutes a day,30-60 minutes a day,Microservices;Automated testing;Observability ...,Other,Appropriate in length,Neither easy nor difficult,23456.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89179,89180,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Bootstrapping a business;Freelance/contr...,"Associate degree (A.A., A.S., etc.)",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
89180,89181,I agree,I am a developer by profession,18-24 years old,"Student, full-time;Employed, part-time","Hybrid (some remote, some in-person)",School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Online Courses or Certification;Othe...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN
89181,89182,I agree,I code primarily as a hobby,Prefer not to say,I prefer not to say,NaN,NaN,Something else,Books / Physical media;Hackathons (virtual or ...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
89182,89183,I agree,I am a developer by profession,Under 18 years old,"Employed, part-time;Student, part-time","Hybrid (some remote, some in-person)",Hobby;School or academic work,"Secondary school (e.g. American high school, G...",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN
89183,89184,I agree,I am a developer by profession,35-44 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Online Courses or Certification;Othe...,Formal documentation provided by the owner of ...,...,Never,1-2 times a week,1-2 times a week,60-120 minutes a day,30-60 minutes a day,DevOps function;Developer portal or other cent...,"Information Services, IT, Software Development...",Appropriate in length,Easy,NaN

In [47]:
df = pd.read_csv('data_sets/data/ETH_1h.csv')

In [48]:
df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [49]:
filt = df['Symbol'] == 'ETHUSD'
filt

0        True
1        True
2        True
3        True
4        True
         ...
23669    True
23670    True
23671    True
23672    True
23673    True
Name: Symbol, Length: 23674, dtype: bool

In [50]:
df.loc[filt]['Volume'].mean()

2011035.2917272113

In [51]:
filt = (df['Open'] > 200) & (df['High'] > 200)

In [52]:
df[filt]

                   Date  Symbol    Open    High     Low   Close      Volume
63     2020-03-11 05-AM  ETHUSD  200.62  200.62  198.32  199.38   817773.68
64     2020-03-11 04-AM  ETHUSD  201.84  202.22  200.62  200.62   580676.70
65     2020-03-11 03-AM  ETHUSD  200.96  202.41  200.32  201.84   504032.33
66     2020-03-11 02-AM  ETHUSD  202.48  202.71  200.51  200.96   510193.41
67     2020-03-11 01-AM  ETHUSD  202.23  202.98  201.35  202.48   788915.78
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[14585 rows x 7 columns]

In [53]:
arr = np.random.randint(1,10, size =(3,3))

In [54]:
arr

array([[5, 2, 2],
       [5, 4, 8],
       [3, 7, 4]])

In [55]:
arr.shape

(3, 3)

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23674 entries, 0 to 23673
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    23674 non-null  object
 1   Symbol  23674 non-null  object
 2   Open    23674 non-null  float64
 3   High    23674 non-null  float64
 4   Low     23674 non-null  float64
 5   Close   23674 non-null  float64
 6   Volume  23674 non-null  float64
dtypes: float64(5), object(2)
memory usage: 1.3+ MB

In [57]:
df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [72]:
df['High'].apply(lambda x: True if x>200 else False)

0        False
1        False
2        False
3        False
4        False
         ...
23669     True
23670     True
23671     True
23672     True
23673     True
Name: High, Length: 23674, dtype: bool

In [40]:
import pandas as pd

# Example DataFrame
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]
})

# Apply a function to each column
result = df.map(lambda x: x**2)
print(result)

   A   B
0  1  16
1  4  25
2  9  36